### PR TITLE
Updated gasdump and lostatsea + 4 new nav files

### PR DESCRIPTION
**Pull request by L1pE**
Gasdump:
- Made drop connections from roof to stairs work more reliably
- Added more jump connections on flipped truck

Lostatsea:
- Removed some blocked drop connections around the map
- Added nav areas to platforms beside the elevator

### CODE REVIEW

**Comment by DevilMudger** [comment]
Isn't hallways the map that's unplayable because the elevator only goes one way? And the mapper lost the vmf?

**Comment by L1pE** [comment]
I kinda wish I knew that was the case before, when I had first tested it I just saw that it was completeable, but now that you mentioned that I tested it again and I see that the elevators don't go back down if you don't get in them in time, oh well.

**Comment by TotallyMehis** [comment]
Also zm_lake crashes but I'll merge it anyway.

**Comment by L1pE** [comment]
Zm_lake never crashes on linux for whatever reason (might be different with more players on, I dunno).

**Comment by DevilMudger** [comment]
I haven't been able to figure out how to reliably reproduce it, but lake does crash fairly consistently when there are multiple players on a server. I've only managed to get it to crash once on a local server with only me in it, and I have no idea what caused it.

**Pull request merged**
